<?php
    session_start();
?>

<!DOCTYPE html>
<html translate="no">
    <head>
        <?php include('_library/lib-include.php')?>
        <title>Strategy | Chess City</title>
        <link rel="shortcut icon" href="_library/image/Logo0.png">
        <link type="text/css" href="_library/css/lessons.css" rel="stylesheet"/>
    </head>
    <body class="basics-wrapper" style="text-align: justify">
        <?php include('_framework/navigation.php') ?>
        <div class="container">
            <div class="top">
                <h2>Chess Strategy</h2>
                <p>Chess strategy is concerned with the evaluation of chess positions and with setting up goals and long-term plans for future play. During the evaluation, players must take into account numerous factors such as the value of the pieces on the board, control of the center and centralization, the pawn structure, king safety, and the control of key squares or groups of squares (for example, diagonals, open files, and dark or light squares). The most basic step in evaluating a position is to count the total value of pieces of both sides. The point values used for this purpose are based on experience; usually, pawns are considered worth one point, knights and bishops about three points each, rooks about five points (the value difference between a rook and a bishop or knight being known as the exchange), and queens about nine points. The king is more valuable than all of the other pieces combined, since its checkmate loses the game. But in practical terms, in the endgame, the king as a fighting piece is generally more powerful than a bishop or knight but less powerful than a rook. These basic values are then modified by other factors like position of the piece (e.g. advanced pawns are usually more valuable than those on their initial squares), coordination between pieces (e.g. a pair of bishops usually coordinate better than a bishop and a knight), or the type of position (e.g. knights are generally better in closed positions with many pawns while bishops are more powerful in open positions). Another important factor in the evaluation of chess positions is pawn structure (sometimes known as the pawn skeleton): the configuration of pawns on the chessboard. Since pawns are the least mobile of the pieces, pawn structure is relatively static and largely determines the strategic nature of the position. Weaknesses in pawn structure include isolated, doubled, or backward pawns and holes; once created, they are often permanent. Care must therefore be taken to avoid these weaknesses unless they are compensated by another valuable asset (for example, by the possibility of developing an attack).</p>
            </div>
            <div class="my-5" style="border-top: 1px solid white">
                <h4 class="d-flex justify-content-center mt-4">Chess Pieces Value</h4>
                <img style="float: left; margin-right: 15px; width: 15%" src="_library/image/strategy1.png">
                <p>A material advantage applies both strategically and tactically. Generally more pieces or an aggregate of more powerful pieces means greater chances of winning. A fundamental strategic and tactical rule is to capture opponent pieces while preserving one's own. Bishops and knights are called minor pieces. A knight is about as valuable as a bishop, but less valuable than a rook. Rooks and the queen are called major pieces. Bishops are usually considered slightly better than knights in open positions, such as toward the end of the game when many of the pieces have been captured, whereas knights have an advantage in closed positions. Having two bishops (the bishop pair) is a particularly powerful weapon, especially if the opposing player lacks one or both of their bishops. Three pawns are likely to be more useful than a knight in the endgame, but in the middlegame, a knight is often more powerful. Two minor pieces are stronger than a single rook, and two rooks are slightly stronger than a queen. The bishop on squares of the same color as the player is slightly more valuable in the opening as it can attack the vulnerable f7/f2-square. A rook is more valuable when doubled with another rook or queen; consequently, doubled rooks are worth more than two unconnected rooks.Under a system like this, giving up a knight or bishop to win a rook ("winning the exchange") is advantageous and is worth about two pawns. This ignores complications such as the current position and freedom of the pieces involved, but it is a good starting point. In an open position, bishops are more valuable than knights (a bishop pair can easily be worth seven points or more in some situations); conversely, in a closed position, bishops are less valuable than knights. However, a knight in the center of the board that cannot be taken is known as a knight outpost and threatens several fork instances. In such a case, a knight is worth far more than a bishop. Also, many pieces have a partner. By doubling up two knights, two rooks, rook and queen or bishop and queen the pieces can get stronger than the sum of the individual pieces alone. When pieces lose their partner, their values slightly decrease. The king is priceless since its capture results in the defeat of that player and brings about the end of that game. However, especially in the endgame, the king can also be a fighting piece, and is sometimes given a fighting value of three and a half points.</p>
            </div>
            <div class="my-5" style="border-top: 1px solid white">
                <h4 class="d-flex justify-content-center mt-4">Control of the Center</h4>
                <img style="float: left; margin-right: 15px; width: 15%" src="_library/image/strategy2.png">
                <p>The strategy consists of placing pieces so that they attack the central four squares of the board. However, a piece being placed on a central square does not necessarily mean it controls the center, e.g., a knight on a central square does not attack any central squares. Conversely, a piece does not have to be on a central square to control the center. For example, the bishop can control the center from afar. Control of the center is generally considered important because tactical battles often take place around the central squares, from where pieces can access most of the board. Center control allows more movement and more possibility for attack and defense. Chess openings try to control the center while developing pieces. Hypermodern openings are those that control the center with pieces from afar (usually the side, such as with a fianchetto); the older Classical (or Modern) openings control it with pawns.</p>
            </div>
            <div class="my-5" style="border-top: 1px solid white">
                <h4 class="d-flex justify-content-center mt-4">Pin and Skewer</h4>
                <img style="float: left; margin-right: 15px; width: 15%" src="_library/image/strategy3.png">
                <p>There are many weapons that a chess player has at his disposal. One of the most lethal attacks is the skewer and pin which attacks a piece and also a piece behind it. This can be done by attacking a king with a piece behind it. The king will be forced to move, exposing the piece behind it. Also if a piece is in front of the king and the piece is pinned, the piece will be unable to move out of the way of harm because of the pin caused on the king. Rarely will you find your opponent at a chess board give you easy skewers or pins that will leave some of his most powerful pieces hanging. Instead, it is imperative that a chess player knows how to set up skewers and pins by using a variety of tricks. These tricks will allow you to take control of a game where you might not have thought you could before.</p>
            </div>
            <div class="my-5" style="border-top: 1px solid white">
                <h4 class="d-flex justify-content-center mt-4">Zugzwang Position</h4>
                <img style="float: left; margin-right: 15px; width: 15%" src="_library/image/strategy4.gif">
                <p>Zugzwang is a situation found in chess and other turn-based games wherein one player is put at a disadvantage because of their obligation to make a move; a player is said to be "in zugzwang" when any legal move will worsen their position. Although the term is used less precisely in games such as chess, it is used specifically in combinatorial game theory to denote a move that directly changes the outcome of the game from a win to a loss. Putting the opponent in zugzwang is a common way to help the superior side win a game, and in some cases it is necessary in order to make the win possible. The term zugzwang was used in German chess literature in 1858 or earlier, and the first known use of the term in English was by World Champion Emanuel Lasker in 1905. The concept of zugzwang was known to chess players many centuries before the term was coined, appearing in an endgame study published in 1604 by Alessandro Salvio, one of the first writers on the game, and in shatranj studies dating back to the early 9th century, over 1000 years before the first known use of the term. Positions with zugzwang occur fairly often in chess endgames, especially in king and pawn endgames. According to John Nunn, positions of reciprocal zugzwang are surprisingly important in the analysis of endgames.</p>
            </div>
            <div class="my-5" style="border-top: 1px solid white">
                <h4 class="d-flex justify-content-center mt-4">Fork</h4>
                <img style="float: left; margin-right: 15px; width: 15%" src="_library/image/strategy5.gif">
                <p>In chess, a fork is a tactic in which a piece attacks two or more pieces simultaneously. The attacker usually aims to capture one of the forked pieces, or threaten checkmate. The defender often finds it difficult to counter two or more threats in a single move. A fork is most effective when it is forcing, such as when the king is put in check. Apart from pawns on an outside file, any piece can fork, but knight forks are the most striking, since, except in the case of other knights, a knight cannot be captured by the piece it is threatening, and, as the knight is considered a minor piece, it can be traded. Since the queen is usually more valuable than the pieces it attacks, a queen fork gains material only when the pieces attacked are undefended or if one of them is the king and the other is undefended.</p>
            </div>
            <div class="my-5" style="border-top: 1px solid white">
                <h4 class="d-flex justify-content-center mt-4">Pawn Structure</h4>
                <img style="float: left; margin-right: 15px; width: 15%" src="_library/image/strategy6.png">
                <p>In chess, the pawn structure (sometimes known as the pawn skeleton) is the configuration of pawns on the chessboard. Because pawns are the least mobile of the chess pieces, the pawn structure is relatively static and thus largely determines the strategic aspect of the position. Weaknesses in the pawn structure, such as isolated, doubled, or backward pawns and holes, once created, are usually permanent. Care must therefore be taken to avoid them (but there are exceptions—for instance see Boleslavsky hole below). In the absence of these structural weaknesses, it is not possible to assess a pawn formation as good or bad—much depends on the position of the pieces. The pawn formation does determine the overall strategies of the players to a large extent, however, even if arising from unrelated openings. Pawn formations symmetrical about a vertical line (such as the e5 Chain and the d5 Chain) may appear similar, but they tend to have entirely different characteristics because of the propensity of the kings to castle on the kingside.</p>
            </div>
            <div class="my-5" style="border-top: 1px solid white">
                <h4 class="d-flex justify-content-center mt-4">Sacrifice</h4>
                <img style="float: left; margin-right: 15px; width: 15%" src="_library/image/strategy7.gif">
                <p>In chess, a sacrifice is a move giving up a piece with the objective of gaining tactical or positional compensation in other forms. A sacrifice could also be a deliberate exchange of a chess piece of higher value for an opponent's piece of lower value. Any chess piece except the king may be sacrificed. Because players usually try to hold on to their own pieces, offering a sacrifice can come as an unpleasant surprise to one's opponent, putting them off balance and causing them to waste precious time trying to calculate whether the sacrifice is sound or not, and whether to accept it. Sacrificing one's queen (the most valuable piece), or a string of pieces, adds to the surprise, and such games can be awarded brilliancy prizes.</p>
            </div>
        </div>
        <?php include('_framework/footer.php') ?>
    </body>
</html>